# Generated by Django 4.2 on 2023-05-01 15:41

from django.db import migrations, models
import django.db.models.deletion
import gayrat.instances


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        blank=True, default="none", max_length=255, null=True
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        blank=True, default="none", max_length=255, null=True
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, default="none", max_length=255, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(default="name kiritilmagan", max_length=255),
                ),
                (
                    "name_en",
                    models.CharField(default="name kiritilmagan", max_length=255),
                ),
                (
                    "name_ru",
                    models.CharField(default="name kiritilmagan", max_length=255),
                ),
                ("description_uz", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_ru", models.TextField(blank=True, null=True)),
                ("count", models.CharField(default="0", max_length=20)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        default="mahsulot kodi kiritilmagan",
                        max_length=30,
                        null=True,
                    ),
                ),
                ("price", models.IntegerField(blank=True, null=True)),
                ("korzinka", models.BooleanField(default=False)),
                ("saralangan", models.BooleanField(default=False)),
                ("solishtirsh", models.BooleanField(default=False)),
                ("best_seller_product", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gayrat.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product",
            },
        ),
        migrations.CreateModel(
            name="ProductShots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=gayrat.instances.get_shots_path)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shots",
                        to="gayrat.product",
                    ),
                ),
            ],
        ),
    ]
