# Generated by Django 4.2 on 2023-04-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
