# Generated by Django 4.2 on 2023-04-25 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Best_seller_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='best_seller_images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='best_seller_images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='best_seller_images/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='best_seller_images/')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='best_seller_images/')),
                ('korzinka', models.BooleanField(default=False)),
                ('saralangan', models.BooleanField(default=False)),
                ('solishtirsh', models.BooleanField(default=False)),
                ('best_seller_product', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Best Seller Products',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='catalog_name')),
            ],
            options={
                'verbose_name_plural': 'catalog',
                'db_table': 'catalog',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
            ],
            options={
                'verbose_name_plural': 'Category_Product',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Form',
            },
        ),
        migrations.CreateModel(
            name='Gallery_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='matn kiritilmagan', max_length=512)),
                ('text', models.TextField(default='matn kiritilmagan')),
                ('img', models.ImageField(upload_to='images/')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery News',
                'verbose_name_plural': 'Gallery News',
            },
        ),
        migrations.CreateModel(
            name='GalleryOnlyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Gallery_Only_Images',
            },
        ),
        migrations.CreateModel(
            name='GalleryPhotos1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='galery_images/')),
            ],
            options={
                'verbose_name_plural': 'Gallery_photos',
            },
        ),
        migrations.CreateModel(
            name='Header_Carusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, default='none', max_length=200, null=True)),
                ('text', models.TextField(blank=True, default='none', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'header_carusel',
            },
        ),
        migrations.CreateModel(
            name='InfoGrafika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal_product', models.CharField(default='40', max_length=30)),
                ('partners', models.CharField(default='10', max_length=30)),
                ('nominal_products', models.CharField(default='40', max_length=30)),
                ('nominal_products_last', models.CharField(default='40', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'infografika',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
                ('text', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
            ],
            options={
                'verbose_name_plural': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_link', models.URLField(blank=True, default='link kiritilmagan', max_length=512, null=True)),
                ('facebook_link', models.URLField(blank=True, default='link kiritilmagan', max_length=512, null=True)),
                ('telegram_link', models.URLField(blank=True, default='link kiritilmagan', max_length=512, null=True)),
                ('youtube_link', models.URLField(blank=True, default='link kiritilmagan', max_length=512, null=True)),
                ('whatsapp_link', models.URLField(blank=True, default='link kiritilmagan', max_length=512, null=True)),
                ('linkedin_link', models.URLField(blank=True, default='link kiritilmagan', max_length=512, null=True)),
                ('twitter_link', models.URLField(blank=True, default='link kiritilmagan', max_length=512, null=True)),
                ('tiktok_link', models.URLField(blank=True, default='link kiritilmagan', max_length=512, null=True)),
                ('pinterest_link', models.URLField(blank=True, default='link kiritilmagan', max_length=512, null=True)),
            ],
            options={
                'verbose_name_plural': 'Social_Networks',
            },
        ),
        migrations.CreateModel(
            name='WorksByKale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
                ('text', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Works_By_Kale',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.categoryproduct')),
            ],
            options={
                'verbose_name_plural': 'Sub_Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('count', models.CharField(default='0', max_length=20)),
                ('code', models.CharField(blank=True, default='mahsulot kodi kiritilmagan', max_length=15, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('korzinka', models.BooleanField(default=False)),
                ('saralangan', models.BooleanField(default=False)),
                ('solishtirsh', models.BooleanField(default=False)),
                ('best_seller_product', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryData1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
                ('text', models.TextField(blank=True, default='matn kiritilmagan', null=True)),
                ('image', models.ManyToManyField(to='basic_app.galleryphotos1')),
            ],
            options={
                'verbose_name_plural': 'Gallery_data',
            },
        ),
    ]
