<<<<<<< HEAD
# Generated by Django 4.2 on 2023-04-29 14:05
=======
# Generated by Django 4.2 on 2023-04-29 13:10
>>>>>>> 9b543d1f4817907c8ec4026081550150577427d3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_name',
            field=models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='location',
            field=models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='phone_number',
            field=models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True),
        ),
<<<<<<< HEAD
        migrations.AddField(
            model_name='discount',
            name='total_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
=======
>>>>>>> 9b543d1f4817907c8ec4026081550150577427d3
    ]
