# Generated by Django 4.2 on 2023-04-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='total_cost',
        ),
    ]
