# Generated by Django 4.2 on 2023-04-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='total_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
