# Generated by Django 4.2 on 2023-04-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_discount_discount_name_discount_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
    ]
