# Generated by Django 4.2 on 2023-04-25 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Best_seller_products',
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='Gallery_News',
        ),
        migrations.RemoveField(
            model_name='gallerydata1',
            name='image',
        ),
        migrations.DeleteModel(
            name='GalleryOnlyImages',
        ),
        migrations.DeleteModel(
            name='Header_Carusel',
        ),
        migrations.DeleteModel(
            name='InfoGrafika',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Partners',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='SocialNetworks',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='WorksByKale',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryProduct',
        ),
        migrations.DeleteModel(
            name='GalleryData1',
        ),
        migrations.DeleteModel(
            name='GalleryPhotos1',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
