# Generated by Django 4.2 on 2023-04-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_alter_discount_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
