# Generated by Django 4.2 on 2023-04-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_discount_total_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
