# Generated by Django 4.2 on 2023-04-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_alter_discount_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='total_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
