# Generated by Django 4.2 on 2023-04-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_chatroom_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='text',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='about',
            name='text_ru',
            field=models.TextField(blank=True, default='matn kiritilmagan', null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='text_uz',
            field=models.TextField(blank=True, default='matn kiritilmagan', null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
