# Generated by Django 4.2 on 2023-04-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_alter_discount_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discount_name',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='total_price',
        ),
    ]
