# Generated by Django 4.2 on 2023-04-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_rename_text_about_text_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='catalog',
            name='name_en',
            field=models.TextField(default='name is not defined', verbose_name='catalog_name'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='name_ru',
            field=models.TextField(default='name is not defined', verbose_name='catalog_name'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='name_uz',
            field=models.TextField(default='name is not defined', verbose_name='catalog_name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, default='none', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, default='none', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(blank=True, default='none', max_length=255, null=True),
        ),
    ]
