# Generated by Django 4.2 on 2023-04-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_user_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.product'),
        ),
    ]
