# Generated by Django 4.2 on 2023-04-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_remove_discount_discount_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_name',
            field=models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='total_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
