# Generated by Django 4.2 on 2023-04-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_rename_name_categoryproduct_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryProduct',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
