# Generated by Django 4.2 on 2023-04-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_discount_total_cost'),
        ('basic_app', '0008_discount_discount_name_discount_total_price'),
    ]

    operations = [
    ]
