# Generated by Django 4.2 on 2023-04-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_remove_subcategory_category_delete_categoryproduct_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
