# Generated by Django 4.2 on 2023-04-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_remove_user_products_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
            ],
            options={
                'verbose_name_plural': 'Discount',
            },
        ),
    ]
