# Generated by Django 4.2 on 2023-04-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_merge_20230429_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='total_cost',
        ),
    ]
