# Generated by Django 4.2 on 2023-04-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_remove_discount_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='total_price',
        ),
    ]
