# Generated by Django 4.2 on 2023-04-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0011_remove_discount_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Discount'},
        ),
    ]
