# Generated by Django 4.2 on 2023-04-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='best_seller_products',
            name='code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
