# Generated by Django 4.2 on 2023-04-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_delete_discount_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub_Category'},
        ),
    ]
