# Generated by Django 4.2 on 2023-04-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_rename_text_gallerydata1_text_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery_news',
            options={'verbose_name': 'Gallery_News', 'verbose_name_plural': 'Gallery_News'},
        ),
        migrations.RenameField(
            model_name='gallery_news',
            old_name='text',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='gallery_news',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='gallery_news',
            name='text_ru',
            field=models.TextField(default='matn kiritilmagan'),
        ),
        migrations.AddField(
            model_name='gallery_news',
            name='text_uz',
            field=models.TextField(default='matn kiritilmagan'),
        ),
        migrations.AddField(
            model_name='gallery_news',
            name='title_ru',
            field=models.CharField(default='matn kiritilmagan', max_length=512),
        ),
        migrations.AddField(
            model_name='gallery_news',
            name='title_uz',
            field=models.CharField(default='matn kiritilmagan', max_length=512),
        ),
    ]
