# Generated by Django 4.2 on 2023-04-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0013_alter_gallery_news_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header_carusel',
            old_name='nomi',
            new_name='nomi_en',
        ),
        migrations.RenameField(
            model_name='header_carusel',
            old_name='text',
            new_name='text_en',
        ),
        migrations.AddField(
            model_name='header_carusel',
            name='nomi_ru',
            field=models.CharField(blank=True, default='none', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='header_carusel',
            name='nomi_uz',
            field=models.CharField(blank=True, default='none', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='header_carusel',
            name='text_ru',
            field=models.TextField(blank=True, default='none', null=True),
        ),
        migrations.AddField(
            model_name='header_carusel',
            name='text_uz',
            field=models.TextField(blank=True, default='none', null=True),
        ),
    ]
