# Generated by Django 4.2 on 2023-04-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0014_alter_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
