# Generated by Django 4.2 on 2023-04-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0014_rename_nomi_header_carusel_nomi_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='best_seller_products',
            name='description',
        ),
        migrations.RemoveField(
            model_name='best_seller_products',
            name='name',
        ),
        migrations.AddField(
            model_name='best_seller_products',
            name='description_en',
            field=models.TextField(blank=True, default='matn kiritilmagan', null=True),
        ),
        migrations.AddField(
            model_name='best_seller_products',
            name='description_ru',
            field=models.TextField(blank=True, default='matn kiritilmagan', null=True),
        ),
        migrations.AddField(
            model_name='best_seller_products',
            name='description_uz',
            field=models.TextField(blank=True, default='matn kiritilmagan', null=True),
        ),
        migrations.AddField(
            model_name='best_seller_products',
            name='name_en',
            field=models.CharField(blank=True, default='nomi kiritilmagan', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='best_seller_products',
            name='name_ru',
            field=models.CharField(blank=True, default='nomi kiritilmagan', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='best_seller_products',
            name='name_uz',
            field=models.CharField(blank=True, default='nomi kiritilmagan', max_length=300, null=True),
        ),
    ]
