# Generated by Django 4.2 on 2023-04-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0014_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
