# Generated by Django 4.2 on 2023-04-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0015_remove_best_seller_products_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='text',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='location',
            name='text_ru',
            field=models.TextField(blank=True, default='matn kiritilmagan', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='text_uz',
            field=models.TextField(blank=True, default='matn kiritilmagan', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='title_ru',
            field=models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='title_uz',
            field=models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True),
        ),
    ]
