# Generated by Django 4.2 on 2023-04-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0017_rename_text_worksbykale_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarabanDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
                ('name_ru', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
                ('name_en', models.CharField(blank=True, default='matn kiritilmagan', max_length=512, null=True)),
            ],
            options={
                'verbose_name_plural': 'Baraban_Discount',
            },
        ),
    ]
