# Generated by Django 4.2 on 2023-05-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0019_alter_product_options_productnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(default='name kiritilmagan', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(default='name kiritilmagan', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_uz',
            field=models.CharField(default='name kiritilmagan', max_length=255),
        ),
    ]
