# Generated by Django 4.2 on 2023-05-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0020_alter_product_name_en_alter_product_name_ru_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image1",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image3",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image4",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image5",
        ),
        migrations.AlterField(
            model_name="category",
            name="name_uz",
            field=models.CharField(default="none", max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_uz",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                blank=True, default="name kiritilmagan", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_ru",
            field=models.CharField(
                blank=True, default="name kiritilmagan", max_length=255, null=True
            ),
        ),
    ]
